version: '3.9'
services:
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: SampleApp_development
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql@123
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: ravteja/app:V1
    # environment:
    # - RAILS_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
            DB_USER: root
            DB_NAME: SampleApp_development
            DB_PASSWORD: mysql@123
            DB_HOST: db

volumes:
  db_data:
