version: '3.9'
services:
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: SampleApp_development
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: ravteja/app:V1
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"

volumes:
  db_data:
